management:
  security:
    enabled: false

server:
  port: 9999
  context-path: /uaa

security:
  sessions: if-required

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/} 
 