eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}
      
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: gateway-service
      client-secret: gateway-service
    resource: 
      user-info-uri: http://localhost:9999/uaa/user
      prefer-token-info: true

zuul: 
  sensitiveHeaders: Cookie,Set-Cookie 
  debug: 
    request: true
  routes: 
    master-data-service: 
      path: /master-data-service/**
      sensitiveHeaders: Cookie,Set-Cookie

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
  
