security:
  sessions: NEVER

server:
  port: 8085
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    org.springframework.security: DEBUG
